version: '3'

services:
  core_api:
    build: .
    container_name: "core-api-container"
    ports:
      - "8000:15400"
    environment:
      - SQLITE_PATH=/genre.db
    volumes:
      - ./app:/app